Updated DwC-MIxS mapping
tdwg/gbwg pull request #78
Opened 2021-12-21 10:11 UTC by raissameyer

This [PR](https://github.com/mapping-commons/sssom/pull/49) and [issue](https://github.com/mapping-commons/sssom/issues/46) in the SSSOM repo showed that - by following the old SSSOM guidance - we have sometimes used the SKOS predicates for narrow match and broad match incorrectly. 

In issue #77 we reviewed the mapping predicates. 

In this PR we updated our mapping files to fix this. 

## Updates for v2.0.0

### Mapping predicates
- value for `predicate_id` updated to `skos:narrowMatch` for the terms listed here: https://github.com/tdwg/gbwg/issues/77#issuecomment-995806725
- value for `predicate_id` updated to `skos:broadMatch` for the terms listed here: https://github.com/tdwg/gbwg/issues/77#issuecomment-995840816
- value for `syntax_predicate_id` updated to `skos:broadMatch` for the terms listed here: https://github.com/tdwg/gbwg/issues/77#issuecomment-997932073, https://github.com/tdwg/gbwg/issues/77#issuecomment-998646738

### Associated metadata
- values for `mapping_date`/`syntax_mapping_date` and `creator_id` updated to reflect the updates in the mapping predicates

### Additional metadata
- v2.0.0 additionally includes a confidence value `confidence`/`syntax_confidence` for the mapping between 0 and 1 (0 no confidence, 1 100% confidence; see [The SSSOM 5-Star System For Mappings](https://mapping-commons.github.io/sssom/spec/#the-sssom-5-star-system-for-mappings)). 

### Removed metadata
- DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv no longer includes the additional column on `predicate_label`

2022-04-07 16:32 UTC, pbuttigieg requested changes
Semantic mapping reviewed in consultation with @raissameyer

2022-04-07 16:32 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:eventDate	Event Date	http://rs.tdwg.org/dwc/terms/Event	skos:narrowMatch	MIXS:0000011	collection_date	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | orcid:0000-0002-2996-719X	dwc:eventDate	dw
Mapping looks good following logic in https://github.com/tdwg/gbwg/issues/77 xref discussion in #17

2022-04-07 16:32 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:sampleSizeValue	Sample Size Value	http://rs.tdwg.org/dwc/terms/Event	skos:broadMatch	MIXS:0000001	samp_size	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | orcid:0000-0002-2996-719X	dwc:sample
Looks fine - this and sampleSizeUnit are semantically (and syntactically) wrapped up in MIxS:samp_size

2022-04-07 16:32 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:associatedTaxa	Associated Taxa	https://dwc.tdwg.org/list/#dwc_Occurrence	skos:broadMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedTaxa	dwcversion:associated
These look fine as they all reference external identifiers. The switch to broadMatch is justified as noted in the comments.

2022-04-07 16:34 UTC, pbuttigieg commented
The review of the semantic mapping (following the update of the SSSOM guidance and @raissameyer's implementation thereof) is done above. 

You'll notice that this was done in a line-by-line fashion as we think this should be the norm for a mapping file that links standards organisations: very thorough, with approvals explicit.

2022-04-08 09:22 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:verbatimCoordinates	Verbatim Coordinates	https://dwc.tdwg.org/list/#dcterms_Location	skos:narrowMatch	MIXS:0000009	lat_lon	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:verbatimCoordinates
Thank you, done.

2022-04-08 09:27 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:verbatimDepth	Verbatim Depth	https://dwc.tdwg.org/list/#dcterms_Location	skos:narrowMatch	MIXS:0000018	depth	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | orcid:0000-0002-2996-719X	dwc:verba
Thank you, I will update the mapping predicate to skos:exactMatch and update the associated comment in the next commit.

2022-04-08 09:34 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:minimumDistanceAboveSurfaceInMeters	Minimum Distance Above Surface in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch	MIXS:0000018	depth	MIxS core	HumanCurated	orcid:0000-0003-
Thank you, I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 09:36 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:maximumDistanceAboveSurfaceInMeters	Maximum Distance Above Surface in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch	MIXS:0000018	depth	MIxS core	HumanCurated	orcid:0000-0003-
Thank you, as discussed I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 10:28 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:minimumDistanceAboveSurfaceInMeters	Minimum Distance Above Surface in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch		alt	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | or
Thank you, as discussed I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 10:29 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:maximumDistanceAboveSurfaceInMeters	Maximum Distance Above Surface in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch		alt	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | or
Thank you, as discussed I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 10:29 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:verbatimElevation	Verbatim Elevation	https://dwc.tdwg.org/list/#dcterms_Location	skos:exactMatch	MIXS:0000093	elev	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:verbatimElevation	dwcversio
Will update the comment in the next commit.

2022-04-08 10:29 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:minimumElevationInMeters	Minimum Elevation in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch	MIXS:0000093	elev	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:minimumElev
Thank you, as discussed I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 10:29 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:maximumElevationInMeters	Maximum Elevation in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch	MIXS:0000093	elev	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:maximumElev
Thank you, as discussed I will update the mapping predicate to skos:narrowMatch and update the associated comment in the next commit.

2022-04-08 10:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:samplingProtocol	Sampling Protocol	http://rs.tdwg.org/dwc/terms/Event	skos:narrowMatch	MIXS:0000002	samp_collect_device	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | orcid:0000-0002-2996-719
Thanks, will update the mapping predicate and comment accordingly.

2022-04-08 10:43 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSemantic-2.0.0.sssom.tsv
> +dwc:samplingProtocol	Sampling Protocol	http://rs.tdwg.org/dwc/terms/Event	skos:narrowMatch	MIXS:0000016	samp_mat_process	MIxS core	HumanCurated	orcid:0000-0003-1144-0290 | orcid:0000-0002-2996-719X	d
Thanks, will update the comment with the next commit.

2022-04-12 16:56 UTC, pbuttigieg requested changes
Syntax review in for your consideration @raissameyer - thanks for the thorough work, almost there!

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:higherGeography	Higher Geography	https://dwc.tdwg.org/list/#dcterms_Location	skos:relatedMatch	MIXS:0000010	geo_loc_name	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:higherGeography	dwcve
Related seems to work, syntactically: both are string lists with some special characters that need not overlap. The controlled vocabs in MIxS don't really impact syntax.

DwC guidance:
>Recommended best practice is to separate the values in a list with space vertical bar space ( | ), with terms in order from least specific to most specific.

DwC examples (extract, that's the actual example of the syntax):
> South America | Argentina | Patagonia | Parque Nacional Nahuel Huapi | Neuquén | Los Lagos

MIxS guidance:
> The geographical origin of the sample as defined by the country or
      sea name followed by specific region name. Country or sea names should be chosen
      from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology
      (http://purl.bioontology.org/ontology/GAZ)

Expected:
>country or sea name (INSDC or GAZ);region(GAZ);specific location name	

value syntax
> {term};{term};{text}

Terms coming from controlled vocabs, with text being uncontrolled

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:higherGeography	Higher Geography	https://dwc.tdwg.org/list/#dcterms_Location	skos:relatedMatch	MIXS:0000010	geo_loc_name	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:higherGeography	dwcve
Perhaps update the comment to focus exclusively on the syntax according to our rubric noted in this review.

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:eventDate	Event Date	http://rs.tdwg.org/dwc/terms/Event	skos:exactMatch	MIXS:0000011	collection_date	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:eventDate	dwcversion:eventDate-2020-08-12
exact is fine, but keep in mind both allow non ISO entries (they just recommend using them). This should be stated in the comment and perhaps we can encourage stricter recommendations to both groups.

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:materialSampleID	Material Sample ID	http://rs.tdwg.org/dwc/terms/MaterialSample	skos:exactMatch	MIXS:0000026	source_mat_id	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:materialSampleID	dw
Both expect PIDs of a sort (undefined / unrestricted as to what kind, that should be noted in the comment) and the universe of their syntax is overlapping to the extent of exactness. Also, the MIxS term references the DwC term, which should also be noted in the comment.

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOrganisms	Associated Organisms	http://rs.tdwg.org/dwc/terms/Organism	skos:relatedMatch	MIXS:0000028	biotic_relationship	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:associatedOr
This is a close candidate for exact match, as both fields accept numbers, letters, and special characters (think candidate phyla names) and, according to the descriptions, also contain structured and paired lists. But the syntax is different enough that we can move from relatedMatch.

Note that DwC expects quoted strings - this may be enough to consider non-exact, but it's borderline as it's "just" the way it structures its lists values. 

We should have a more descriptive comment about the syntactic overlap (characters and structure)

Note the MIxS description diverges from the examples of usage, more here: https://github.com/GenomicsStandardsConsortium/mixs/issues/168

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:sampleSizeUnit	Sample Size Unit	http://rs.tdwg.org/dwc/terms/Event	skos:relatedMatch	MIXS:0000001	samp_size	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:sampleSizeUnit	dwcversion:sampleSi
Would these not be broadMatch cases? MIxS having more (undesirable) syntactic complexity than DwC?

xref: https://github.com/tdwg/gbwg/issues/54#issuecomment-821155504

2022-04-12 16:56 UTC, pbuttigieg commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:samplingProtocol	Sampling Protocol	http://rs.tdwg.org/dwc/terms/Event	skos:relatedMatch	MIXS:0000016	samp_mat_process	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:samplingProtocol	dwcvers
These may be cases of DwC narrowMatch to MIxS as the DwC description calls for a higher diversity of strings. However, the MIxS term "label" and its description can also be read as quite unbounded. Either the related or narrowMatch would be fine in IMO, but we should add some more qualification to the comment.

2022-04-12 21:00 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:country	Country	https://dwc.tdwg.org/list/#dcterms_Location	skos:relatedMatch	MIXS:0000010	geo_loc_name	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:country	dwcversion:country-2017-10-06
Thank you, comment and mapping will be updated in the next commit.

2022-04-12 21:00 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:waterBody	Water Body	https://dwc.tdwg.org/list/#dcterms_Location	skos:relatedMatch	MIXS:0000010	geo_loc_name	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:waterBody	dwcversion:waterBody-20
Thank you, comment and mapping will be updated in the next commit.

2022-04-12 21:00 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:maximumElevationInMeters	Maximum Elevation in Meters	https://dwc.tdwg.org/list/#dcterms_Location	skos:broadMatch	MIXS:0000093	elev	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:maximumElev
Comments will be updated in the next commit.

2022-04-12 21:04 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:higherGeography	Higher Geography	https://dwc.tdwg.org/list/#dcterms_Location	skos:relatedMatch	MIXS:0000010	geo_loc_name	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:higherGeography	dwcve
Thank you. Comment, with a link to the rubric set up above, updated in the next commit.

2022-04-12 21:04 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:eventDate	Event Date	http://rs.tdwg.org/dwc/terms/Event	skos:exactMatch	MIXS:0000011	collection_date	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:eventDate	dwcversion:eventDate-2020-08-12
Thank you for noting this. Captured the fact that both only note ISO entries as a recommendation in the comment.

2022-04-12 21:17 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOrganisms	Associated Organisms	http://rs.tdwg.org/dwc/terms/Organism	skos:relatedMatch	MIXS:0000028	biotic_relationship	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:associatedOr
Thanks. Comment updated in the next commit.

2022-04-12 21:26 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:samplingProtocol	Sampling Protocol	http://rs.tdwg.org/dwc/terms/Event	skos:relatedMatch	MIXS:0000016	samp_mat_process	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:samplingProtocol	dwcvers
Thank you. 

I would argue to stick with relatedMatch, as the MIxS term and its expected syntax is too loosely defined to narrow down the expected diversity of strings. Indeed, the MIxS field is on a similar level as the verbatim fields above, which we decided to related to other terms with `relatedMatch` as they can have free text (or any other string-based value) as syntax.

2022-04-12 21:35 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:sampleSizeUnit	Sample Size Unit	http://rs.tdwg.org/dwc/terms/Event	skos:relatedMatch	MIXS:0000001	samp_size	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dwc:sampleSizeUnit	dwcversion:sampleSi
Thank you for catching this. Updated in next commit.

2022-04-12 21:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOrganisms	Associated Organisms	https://dwc.tdwg.org/list/#dwc_Organism	skos:relatedMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedOrganisms	dwcver
Thank you. Updated in the coming commit.

2022-04-12 21:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedSequences	Associated Sequences	https://dwc.tdwg.org/list/#dwc_Occurrence	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedSequences	dwcver
Thank you. Updated in the coming commit.

2022-04-12 21:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOccurrences	Associated Occurrences	https://dwc.tdwg.org/list/#dwc_Organism	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedOccurrences	dw
Thank you. Updated in the coming commit.

2022-04-12 21:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedMedia	Associated Media	https://dwc.tdwg.org/list/#dwc_Occurrence	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedMedia	dwcversion:associa
Thank you. Updated in the coming commit.

2022-04-12 21:41 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dcterms:references	References	https://dwc.tdwg.org/list/#dcterms_references	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dcterms:references	dcversion:#references-
Thank you. Updated in the coming commit.

2022-04-12 21:42 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedMedia	Associated Media	https://dwc.tdwg.org/list/#dwc_Occurrence	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedMedia	dwcversion:associa
Thank you. Updated in the coming commit.

2022-04-12 23:10 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOccurrences	Associated Occurrences	https://dwc.tdwg.org/list/#dwc_Organism	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedOccurrences	dw
Thank you. Updated in the coming commit.

2022-04-12 23:10 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedOrganisms	Associated Organisms	https://dwc.tdwg.org/list/#dwc_Organism	skos:relatedMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedOrganisms	dwcver
Thank you. Updated in the coming commit.

2022-04-12 23:10 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dwc:associatedMedia	Associated Media	https://dwc.tdwg.org/list/#dwc_Occurrence	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0002-2996-719X	dwc:associatedMedia	dwcversion:associa
Thank you. Updated in the coming commit.

2022-04-12 23:10 UTC, raissameyer commented on dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv
> +dcterms:references	References	https://dwc.tdwg.org/list/#dcterms_references	skos:exactMatch	MIXS:0000091	url	MIxS core	HumanCurated	orcid:0000-0003-1144-0290	dcterms:references	dcversion:#references-
Thank you. Updated in the coming commit.

2022-04-12 23:14 UTC, raissameyer commented
Thank you for the in depth review @pbuttigieg. I have addressed the comments as discussed, and updated the semantic and syntactic mapping file accordingly. 

Please let me know if there are any further comments.

Once we are good to go, I'll go ahead and also update the Support mapping file to reflect the changes in the semantic and syntactic mapping.

2022-10-04 14:13 UTC, merged